version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  frontend:
    build:
      context: ./
      dockerfile: front.Dockerfile
    volumes:
      - ./frontend:/var/www/html
    environment:
      - VIRTUAL_HOST=front.local
    ports:
      - "81:80"
      - "4433:443"

#  backend:
#    build:
#      context: ./
#      dockerfile: back.Dockerfile
#    volumes:
#      - ./backend:/var/www/html
#    environment:
#       - VIRTUAL_HOST=backend.local
#    ports:
#      - "82:80"
#      - "4431:443"
#
#volumes:
#  dbdata:
